sudo: required
services:
  - docker

before_install:
  - docker build -t jasonnguyen/docker-react-sample -f Dockerfile.dev .

scripts:
  - docker run jasonnguyen/docker-react-sample npm run test -- --coverage
