sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jasonnguyen/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true jasonnguyen/docker-react-sample npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-react-sample'
  env: 'Dockerreactsample-env-1'
  bucket_name: 'elasticbeanstalk-us-west-1-353952151937'
  bucker_path: 'docker-react-sample'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
