sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jasonnguyen/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true jasonnguyen/docker-react-sample npm run test
